# Element types
GKP = 1
DEF = 2
MID = 3
FWD = 4
MNG = 5

ELEMENT_TYPES = {
    GKP: "GKP",
    DEF: "DEF",
    MID: "MID",
    FWD: "FWD",
    MNG: "MNG",
}

# Squad selection rules
NUM_SQUAD_GKPS = 2
NUM_SQUAD_DEFS = 5
NUM_SQUAD_MIDS = 5
NUM_SQUAD_FWDS = 3

NUM_SQUAD_PLAYERS = NUM_SQUAD_GKPS + NUM_SQUAD_DEFS + NUM_SQUAD_MIDS + NUM_SQUAD_FWDS

NUM_STARTING_XI = 11

NUM_STARTING_XI_GKPS = 1

MIN_STARTING_XI_GKPS = 1
MIN_STARTING_XI_DEFS = 3
MIN_STARTING_XI_MIDS = 0
MIN_STARTING_XI_FWDS = 1

MAX_STARTING_XI_GKPS = 1
MAX_STARTING_XI_DEFS = 5
MAX_STARTING_XI_MIDS = 5
MAX_STARTING_XI_FWDS = 3

MAX_PLAYERS_PER_TEAM = 3

# Transfer rules
STARTING_BUDGET = 1000
TRANSFER_COST = 4
MAX_FREE_TRANSFERS = 5

# Scoring rules
CAPTAIN_MULTIPLIER = 2.0
