OPTIMIZATION_WINDOW_SIZE = 1
ROUND_DECAY = 1.0
STARTING_XI_MULTIPLIER = 1.0
VICE_CAPTAIN_MULTIPLIER = 1.0
RESERVE_GKP_MULTIPLIER = 0.0
RESERVE_OUT_1_MULTIPLIER = 0.0
RESERVE_OUT_2_MULTIPLIER = 0.0
RESERVE_OUT_3_MULTIPLIER = 0.0
