import numpy as np


SQUAD_EVALUATION_ROUND_FACTOR = 1.0

CAPTAIN_MULTIPLIER = 2
STARTING_XI_MULTIPLER = 1
RESERVE_GKP_MULTIPLIER = 0
RESERVE_OUT_MULTIPLIER = 0.4 ** np.arange(1, 4)

FUTURE_GAMEWEEKS_EVALUATED = 8